service: facebookmessenger

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

# You can overwrite defaults by adding the following
#  stage: dev
#  region: us-east-1

# Add one function for each Lambda
functions:
  webhook: # Lambda that gets triggered when user starts a conversation
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: GET # This webhook lambda is called by Facebook to verify the tokens
          integration: lambda
      - http:
          path: webhook
          method: POST # On POST, this lambda talks to the cognicity server to fetch unique cardId, constructs a response and sends the card OTL to the user
          integration: lambda
  reply: # Lambda that gets triggered when a message is published to the SNS topic Facebook
    handler: handler.reply
    events:
      - sns: Facebook
